# Generated by Django 4.2.6 on 2023-12-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_details_email_alter_details_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='Students',
        ),
    ]
